2018-11-06 10:12:49[12] ERROR index (null) - 
AppName=WebApi
LogTime=2018/11/6 10:12:49
Title=Unknown column 'DoctorCode' in 'where clause'
Message=Message:Unknown column 'DoctorCode' in 'where clause'
RequestParm:{"OrderCode":null,"DoctorCode":"D201810100000001","ServiceCode":"S201811030000001","CustomerCode":"C18101600000001","Name":"test","Mobile":"123","Gender":1,"Age":12,"LocatedCity":"test","Description":"test","ExpectTime":"0001-01-01T00:00:00","CouponCode":null,"OriginAmount":1000.0,"OrderAmount":1000.0,"DiscountAmount":0.0,"AmountType":1,"DepositAmount":0.0,"ImgList":null,"UserID":31,"WechatOpenID":null,"PayAmount":0.0}
TargetSite:Void OnOperationException(BLToolkit.Data.OperationType, BLToolkit.Data.DataException)
Data:
StackTrace:   在 BLToolkit.Data.DbManager.OnOperationException(OperationType op, DataException ex)
   在 BLToolkit.Data.DbManager.HandleOperationException(OperationType op, Exception ex)
   在 BLToolkit.Data.DbManager.ExecuteOperation[T](OperationType operationType, Func`1 operation)
   在 BLToolkit.Data.DbManager.ExecuteReaderInternal(CommandBehavior commandBehavior)
   在 BLToolkit.Data.DbManager.ExecuteReader(CommandBehavior commandBehavior)
   在 BLToolkit.Data.DbManager.ExecuteReaderInternal()
   在 BLToolkit.Data.DbManager.ExecuteObjectInternal(Object entity, Type type, Object[] parameters)
   在 BLToolkit.Data.DbManager.ExecuteObject[T]()
   在 DAL.OpeServiceOrder_DAL.AddServiceOrder(AddServiceOrder_Model model) 位置 D:\work\DAL\OpeServiceOrder_DAL.cs:行号 386
   在 BLL.OpeServiceOrder_BLL.AddServiceOrder(AddServiceOrder_Model model) 位置 D:\work\BLL\OpeServiceOrder_BLL.cs:行号 58
   在 WebApi.Controllers.Touch.OrderController.AddServiceOrder(JObject obj) 位置 D:\work\WebApi\Controllers\Touch\OrderController.cs:行号 213
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()

ProcessName=dyapi
ClientIp=10.0.0.122
ServerIp=10.0.0.122
UrlReferrer=
RawUrl=/Order/AddServiceOrder
Header=Content-Length:422
Content-Type:application/json
Accept-Charset:UTF-8
Authorization:99314D433309CBCC4E1169B287F73EC8
Expect:100-continue
Host:www.dyapi.com
Accept-Languag:zh-cn
US:0
ME:ADDSERVICEORDER
TI:2018/11/6 10:12:49


2018-11-06 10:15:56[39] ERROR index (null) - 
AppName=WebApi
LogTime=2018/11/6 10:15:56
Title=Unknown column 'DoctorCode' in 'where clause'
Message=Message:Unknown column 'DoctorCode' in 'where clause'
RequestParm:{"OrderCode":null,"DoctorCode":"D201810100000001","ServiceCode":"S201811030000001","CustomerCode":"C18101600000001","Name":"test","Mobile":"123","Gender":1,"Age":12,"LocatedCity":"test","Description":"test","ExpectTime":"0001-01-01T00:00:00","CouponCode":null,"OriginAmount":1000.0,"OrderAmount":1000.0,"DiscountAmount":0.0,"AmountType":1,"DepositAmount":0.0,"ImgList":null,"UserID":31,"WechatOpenID":null,"PayAmount":0.0}
TargetSite:Void OnOperationException(BLToolkit.Data.OperationType, BLToolkit.Data.DataException)
Data:
StackTrace:   在 BLToolkit.Data.DbManager.OnOperationException(OperationType op, DataException ex)
   在 BLToolkit.Data.DbManager.HandleOperationException(OperationType op, Exception ex)
   在 BLToolkit.Data.DbManager.ExecuteOperation[T](OperationType operationType, Func`1 operation)
   在 BLToolkit.Data.DbManager.ExecuteReaderInternal(CommandBehavior commandBehavior)
   在 BLToolkit.Data.DbManager.ExecuteReader(CommandBehavior commandBehavior)
   在 BLToolkit.Data.DbManager.ExecuteReaderInternal()
   在 BLToolkit.Data.DbManager.ExecuteObjectInternal(Object entity, Type type, Object[] parameters)
   在 BLToolkit.Data.DbManager.ExecuteObject[T]()
   在 DAL.OpeServiceOrder_DAL.AddServiceOrder(AddServiceOrder_Model model) 位置 D:\work\DAL\OpeServiceOrder_DAL.cs:行号 386
   在 BLL.OpeServiceOrder_BLL.AddServiceOrder(AddServiceOrder_Model model) 位置 D:\work\BLL\OpeServiceOrder_BLL.cs:行号 58
   在 WebApi.Controllers.Touch.OrderController.AddServiceOrder(JObject obj) 位置 D:\work\WebApi\Controllers\Touch\OrderController.cs:行号 213
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()

ProcessName=dyapi
ClientIp=10.0.0.122
ServerIp=10.0.0.122
UrlReferrer=
RawUrl=/Order/AddServiceOrder
Header=Connection:Keep-Alive
Content-Length:422
Content-Type:application/json
Accept-Charset:UTF-8
Authorization:99314D433309CBCC4E1169B287F73EC8
Expect:100-continue
Host:www.dyapi.com
Accept-Languag:zh-cn
US:0
ME:ADDSERVICEORDER
TI:2018/11/6 10:15:56


2018-11-06 16:49:47[15] ERROR index (null) - 
AppName=WebApi
LogTime=2018/11/6 16:49:47
Title=WxPayData内部含有值为null的字段!
Message=Message:WxPayData内部含有值为null的字段!
RequestParm:{"OrderCode":null,"DoctorCode":"D201810100000001","ServiceCode":"S201811030000001","CustomerCode":"C18101600000001","Name":"test","Mobile":"123","Gender":1,"Age":123,"LocatedCity":"test","Description":"test","ExpectTime":"2018-11-06T00:00:00","CouponCode":null,"OriginAmount":10.0,"OrderAmount":10.0,"DiscountAmount":0.0,"AmountType":1,"DepositAmount":0.0,"DiscountFlg":true,"ImgList":null,"UserID":31,"LevelID":1,"WechatOpenID":null,"PayAmount":0.0}
TargetSite:System.String ToUrl()
Data:
StackTrace:   在 Common.WeChat.lib.WxPayData.ToUrl() 位置 D:\work\Common\WeChat\lib\Data.cs:行号 166
   在 Common.WeChat.lib.WxPayData.MakeSign() 位置 D:\work\Common\WeChat\lib\Data.cs:行号 213
   在 Common.WeChat.WeChatPay.UnifiedOrder(String out_trade_no, String body, Int32 total_fee, String openid, String notify_url) 位置 D:\work\Common\WeChat\WeChatPay.cs:行号 35
   在 WebApi.Controllers.Touch.OrderController.AddServiceOrder(JObject obj) 位置 D:\work\WebApi\Controllers\Touch\OrderController.cs:行号 231
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()

ProcessName=dyapi
ClientIp=10.0.0.122
ServerIp=10.0.0.122
UrlReferrer=
RawUrl=/Order/AddServiceOrder
Header=Content-Length:450
Content-Type:application/json
Accept-Charset:UTF-8
Authorization:57E919AA717A29B251DC5BEF9732F4BE
Expect:100-continue
Host:www.dyapi.com
Accept-Languag:zh-cn
US:0
ME:ADDSERVICEORDER
TI:2018/11/6 16:49:46


2018-11-06 16:51:06[6] ERROR index (null) - 
AppName=WebApi
LogTime=2018/11/6 16:51:06
Title=WxPayData内部含有值为null的字段!
Message=Message:WxPayData内部含有值为null的字段!
RequestParm:{"OrderCode":null,"DoctorCode":"D201810100000001","ServiceCode":"S201811030000001","CustomerCode":"C18101600000001","Name":"test","Mobile":"123","Gender":1,"Age":123,"LocatedCity":"test","Description":"test","ExpectTime":"2018-11-06T00:00:00","CouponCode":null,"OriginAmount":10.0,"OrderAmount":10.0,"DiscountAmount":0.0,"AmountType":1,"DepositAmount":0.0,"DiscountFlg":true,"ImgList":null,"UserID":31,"LevelID":1,"WechatOpenID":null,"PayAmount":0.0}
TargetSite:System.String ToUrl()
Data:
StackTrace:   在 Common.WeChat.lib.WxPayData.ToUrl() 位置 D:\work\Common\WeChat\lib\Data.cs:行号 166
   在 Common.WeChat.lib.WxPayData.MakeSign() 位置 D:\work\Common\WeChat\lib\Data.cs:行号 213
   在 Common.WeChat.WeChatPay.UnifiedOrder(String out_trade_no, String body, Int32 total_fee, String openid, String notify_url) 位置 D:\work\Common\WeChat\WeChatPay.cs:行号 35
   在 WebApi.Controllers.Touch.OrderController.AddServiceOrder(JObject obj) 位置 D:\work\WebApi\Controllers\Touch\OrderController.cs:行号 231
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()

ProcessName=dyapi
ClientIp=10.0.0.122
ServerIp=10.0.0.122
UrlReferrer=
RawUrl=/Order/AddServiceOrder
Header=Content-Length:450
Content-Type:application/json
Accept-Charset:UTF-8
Authorization:57E919AA717A29B251DC5BEF9732F4BE
Expect:100-continue
Host:www.dyapi.com
Accept-Languag:zh-cn
US:0
ME:ADDSERVICEORDER
TI:2018/11/6 16:50:38


