2018-11-07 11:46:24[7] ERROR index (null) - 
AppName=WebApi
LogTime=2018/11/7 11:46:24
Title=未将对象引用设置到对象的实例。
Message=Message:未将对象引用设置到对象的实例。
RequestParm:{"CustomerCode":"C18101600000001"}
TargetSite:Model.Operate_Model.CustomerInfo_Model GetCustomerInfo(System.String)
Data:
StackTrace:   在 DAL.InfCustomer_DAL.GetCustomerInfo(String CustomerCode) 位置 D:\work\DAL\InfCustomer_DAL.cs:行号 291
   在 BLL.InfCustomer_BLL.GetCustomerInfo(String CustomerCode) 位置 D:\work\BLL\InfCustomer_BLL.cs:行号 54
   在 WebApi.Controllers.Touch.MemberController.GetCustomerInfo(JObject obj) 位置 D:\work\WebApi\Controllers\Touch\MemberController.cs:行号 553
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()

ProcessName=dyapi
ClientIp=10.0.0.122
ServerIp=10.0.0.122
UrlReferrer=
RawUrl=/Member/GetCustomerInfo
Header=Connection:Keep-Alive
Content-Length:34
Content-Type:application/json
Accept-Charset:UTF-8
Authorization:C644AA6072B15348BE98F7133C747BC8
Expect:100-continue
Host:www.dyapi.com
Accept-Languag:zh-cn
US:0
ME:GETCUSTOMERINFO
TI:2018/11/7 11:46:19


2018-11-07 15:00:46[12] ERROR index (null) - 
AppName=WebApi
LogTime=2018/11/7 15:00:46
Title=未将对象引用设置到对象的实例。
Message=Message:未将对象引用设置到对象的实例。
RequestParm:{"CustomerCode":"C18101600000001"}
TargetSite:Model.Operate_Model.CustomerInfo_Model GetCustomerInfo(System.String)
Data:
StackTrace:   在 DAL.InfCustomer_DAL.GetCustomerInfo(String CustomerCode) 位置 D:\work\DAL\InfCustomer_DAL.cs:行号 291
   在 BLL.InfCustomer_BLL.GetCustomerInfo(String CustomerCode) 位置 D:\work\BLL\InfCustomer_BLL.cs:行号 54
   在 WebApi.Controllers.Touch.MemberController.GetCustomerInfo(JObject obj) 位置 D:\work\WebApi\Controllers\Touch\MemberController.cs:行号 553
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()

ProcessName=dyapi
ClientIp=10.0.0.122
ServerIp=10.0.0.122
UrlReferrer=
RawUrl=/Member/GetCustomerInfo
Header=Content-Length:34
Content-Type:application/json
Accept-Charset:UTF-8
Authorization:C644AA6072B15348BE98F7133C747BC8
Expect:100-continue
Host:www.dyapi.com
Accept-Languag:zh-cn
US:0
ME:GETCUSTOMERINFO
TI:2018/11/7 15:00:46


2018-11-07 15:18:09[53] ERROR index (null) - 
AppName=WebApi
LogTime=2018/11/7 15:18:09
Title=未将对象引用设置到对象的实例。
Message=Message:未将对象引用设置到对象的实例。
RequestParm:{"CustomerCode":"C18101600000001"}
TargetSite:Model.Operate_Model.CustomerInfo_Model GetCustomerInfo(System.String)
Data:
StackTrace:   在 DAL.InfCustomer_DAL.GetCustomerInfo(String CustomerCode) 位置 D:\work\DAL\InfCustomer_DAL.cs:行号 291
   在 BLL.InfCustomer_BLL.GetCustomerInfo(String CustomerCode) 位置 D:\work\BLL\InfCustomer_BLL.cs:行号 54
   在 WebApi.Controllers.Touch.MemberController.GetCustomerInfo(JObject obj) 位置 D:\work\WebApi\Controllers\Touch\MemberController.cs:行号 553
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()

ProcessName=dyapi
ClientIp=10.0.0.122
ServerIp=10.0.0.122
UrlReferrer=
RawUrl=/Member/GetCustomerInfo
Header=Connection:Keep-Alive
Content-Length:34
Content-Type:application/json
Accept-Charset:UTF-8
Authorization:C644AA6072B15348BE98F7133C747BC8
Expect:100-continue
Host:www.dyapi.com
Accept-Languag:zh-cn
US:0
ME:GETCUSTOMERINFO
TI:2018/11/7 15:18:09


